version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    command: --default-authentication-plugin=mysql_native_password --server-id=1 --log-bin=mysql-bin --binlog-format=ROW
    volumes:
      - mysql_data:/var/lib/mysql

  express:
    build:
      context: ./server
    container_name: express-server
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./server:/app
    environment:
      DB_HOST: mysql
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: testdb

volumes:
  mysql_data:
